### ISSUE TITLE
Incorrect behavior of backslash in regexp filter

### ISSUE THREAD

**Issue by somebody1234** [torrent-file-editor/torrent-file-editor#108]
self explanatory.

**Comment by somebody1234** [comment]
also proper & more intuitive regex support would be nice.

**Comment by drizt** [comment]
What wrong with current regexp now?

**Comment by somebody1234** [comment]
very counterintuitive. `\` doesn't work either, and **matching files are hidden rather than kept**. although maybe that's a problem with filter in general.

**Comment by drizt** [comment]
> matching files are hidden

Matching files are removed from the list. You can't *unhide* them. Only add them again.

What means:

> \ doesn't work either

?

**Comment by somebody1234** [comment]
\ is normally used to escape special characters in the regex; however it matches literal \ only in the regex

**Comment by drizt** [comment]
`\` works for me.

For example I added 3 files `Hello`, `HelloWorld` and `Hello World`. With `Hello\b` will be removed `Hello` and `Hello World` but not `HelloWorld`. Also I tested `\(` regexp on `file (name)` filename. File was removed. See [here](https://doc.qt.io/qt-5/qregexp.html) how works Qt regexp.

**Comment by somebody1234** [comment]
however when i do `\..._` for a 3 digit filename it works. iirc with `\\..._` it didn't

**Comment by drizt** [comment]
I don't understand you. Which regexp on which filename you tries to apply? You can provide a screenshot. Please avoid me to ask you a tons of questions to try understand your problem. I suggest you to read something like [that](https://sqa.stackexchange.com/questions/1920/best-guidelines-for-bug-reporting).

> Nothing can ruin your day like a poorly-written bug report.

**Comment by somebody1234** [comment]
`\..._` matches a 3 digit filename. for example `path\to\my\file\000_a.jpg`. however `\\..._` does ***not*** match. same with, e.g. `\75` matching; `\\75` does ***not***. 
![image](https://user-images.githubusercontent.com/4046547/97439111-7c291c80-1971-11eb-96b9-8c2f9dd04a9a.png)
this does not work. i have clicked the filter button multiple times.
![image](https://user-images.githubusercontent.com/4046547/97439162-8c40fc00-1971-11eb-93e8-a1ddee86bfc6.png)
this works perfectly fine. note that this is an ***unescaped*** backslash.
![image](https://user-images.githubusercontent.com/4046547/97439238-a4188000-1971-11eb-9d99-4e7da1645d3d.png)
this is no different from special chars.
![image](https://user-images.githubusercontent.com/4046547/97439266-ad095180-1971-11eb-973e-263af96f8cdd.png)
using ***unescaped*** backslash again.

**Comment by drizt** [comment]
Try to use normal slah `/` not backslash `\`. Internally for filenames a used `/`. So when you see `path\to\my\file\000_a.jpg` TFE recognize it as `path/to/my/file/000_a.jpg`.

**Comment by somebody1234** [comment]
ok so that works as well. however it is still true that backslash just doesn't work in general:
![image](https://user-images.githubusercontent.com/4046547/97554260-3aa47a00-1a22-11eb-9053-95d6a47f6c11.png)
![image](https://user-images.githubusercontent.com/4046547/97554279-409a5b00-1a22-11eb-8a66-d8d20e52e37e.png)
![image](https://user-images.githubusercontent.com/4046547/97554303-4b54f000-1a22-11eb-9608-af68bba19278.png)

**Comment by drizt** [comment]
`_p\d` workd for me.

**Comment by drizt** [comment]
I try to fix this. Check this builds https://dropmefiles.com/d1xdD

**Comment by somebody1234** [comment]
seems like the issue is still there on both x32 and x64 (checked for the `p\d` issue)

**Comment by drizt** [comment]
Check `\\`.

**Comment by somebody1234** [comment]
`\\` path delimiter works now, however for some reason entering just `\\` (and `p.` on a directory with filenames containing`p0`-`p9`) restores all results for some reason. also turns out a lot of other regex features just don't work, like `^` and `.`

**Comment by drizt** [comment]
![изображение](https://user-images.githubusercontent.com/534665/97806040-76864c00-1c7b-11eb-8585-d8408423cbb4.png)

Here I use red lines for files which will be delete with regex template `p_\d`. I checked TFE on Windows 7 64-bit.

**Comment by drizt** [comment]
It's bad practice to use a single issue for several task. Here task for regexp files filter. So I will rename current. Please open a new issue for lexicographical sorting order. Also a litle advice for you for future try to use a short issue title and detailed explanation in task body. Never use *self explanatory*.

**Comment by drizt** [comment]
Also please create a new task for *inverted* filter which keeps files instead of removing.
