### ISSUE TITLE
Cannot change path in resume.dat for multiple torrents

### ISSUE THREAD

**Issue by jeffrey-lebowski** [torrent-file-editor/torrent-file-editor#115]
Thanks for creating, maintaining and sharing this software.

I would like to edit Bittorrent resume.dat in order to change the current path of the .torrent file directory. This can be done with your tool by **manually** editing the Key fields containing the path, but I'm looking for a faster way as I have 100s of torrent paths to edit...

It seems that this would require editing only a part of the Key that contains the path and I wasn't able to achieve this with wildcards/or regex here. My regex expression matched all Key entries correctly with `A:\\TORRENTS\\.*\.torrent,` but the tool would not replace them with `B:\\NEW\\TORRENTS\\.*\.torrent`.

Example of what I want to do.
  I want to change this:

    A:\TORRENTS\<torrent 1 name>.torrent
    A:\TORRENTS\<torrent 2 name>.torrent
    .....
    A:\TORRENTS\<torrent 1000 name>.torrent

  To this:

    B:\NEW\TORRENTS\<torrent 1 name>.torrent
    B:\NEW\TORRENTS\<torrent 2 name>.torrent
    .....
    B:\NEW\TORRENTS\<torrent 1000 name>.torrent

Is this possible with your tool and if so, could you please explain how?

**Comment by drizt** [comment]
I think you can open **Raw** tab, copy all text to any text editor, replace text *A:\TORRENTS\* with *B:\NEW\TORRENTS\* and paste modified text back to **Raw** tab.

P.S. atm TFE has Replace feature. But it can't change part of value only whole value. But it not you case. You can attach any resume.dat with paths for example. It helps me to improve replace functional.

**Comment by jeffrey-lebowski** [comment]
Unfortunately, the file doesn't open in the Raw tab at all. It's permanently stuck at "Not Responding". I presume that is because the file size is too large for it to show (=15MB).

Find an example resume.dat [here](https://1fichier.com/?x649hfmi7hpt6pxb3p2m). Please make a copy of it and let me know when you do, because I might delete it later.

Many thanks for your help with this matter.

**Comment by drizt** [comment]
Try to use TFE in command line.

`torrent-file-editor.exe --to-json resume.dat resume.json`.

Edit as text and then convert back to bencode format with

`torrent-file-editor.exe --from-json resume.json resume.dat`.

**Comment by jeffrey-lebowski** [comment]
The method you suggested works perfectly and it's very fast/efficient too. Thanks.

For anyone attempting this in the future: (1) always make a copy of your original `resume.dat` before doing anything (torrent clients overwrite that file every time they're launched); (2) remember to remove the `.fileguard` key in the Tree view (this should be the first entry under `root`) **before** using the modified `resume.dat` in the torrent client. Otherwise the torrent client will recognize that the file has been tampered with and it won't work.
