### ISSUE TITLE
Troubles when building, failed at the make command

### ISSUE THREAD

**Issue by danieldeankon** [torrent-file-editor/torrent-file-editor#116]
### Summary

For Linux Qt5, Qt5LinguistTools which is present in package `qttools5-dev` was required. It would be good to have that specified in the readme as an explicit dependency.

I was not able to build the project. I assume some of my tools are outdated, but I don't know which ones (Edit: The issue was that gcc version 9 was required). It would be good to have minimum versions of the necessary tools specified in the readme.

### Versions

`cmake`: cmake version 3.10.2

`gcc`: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

`qmake` and `qt`: QMake version 3.1
Using Qt version 5.9.5 in /usr/lib/x86_64-linux-gnu

`make`: GNU Make 4.1
Built for x86_64-pc-linux-gnu

### Log

Inside directory `torrent-file-editor/build` ran command `$ cmake -DCMAKE_BUILD_TYPE=Release -DQT5_BUILD=ON ..` with output:

```bash
CMake Error at CMakeLists.txt:112 (find_package):
  By not providing "FindQt5LinguistTools.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5LinguistTools", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5LinguistTools"
  with any of the following names:

    Qt5LinguistToolsConfig.cmake
    qt5linguisttools-config.cmake

  Add the installation prefix of "Qt5LinguistTools" to CMAKE_PREFIX_PATH or
  set "Qt5LinguistTools_DIR" to a directory containing one of the above
  files.  If "Qt5LinguistTools" provides a separate development package or
  SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/home/daniel/git/torrent-file-editor/build/CMakeFiles/CMakeOutput.log".
```

Ran command `$ sudo apt install qttools5-dev` then was able to run `$ cmake -DCMAKE_BUILD_TYPE=Release -DQT5_BUILD=ON ..` successfully

Ran command `make` which failed at:

(some output omitted)

```bash
[ 68%] Building CXX object CMakeFiles/torrent-file-editor.dir/bencodemodel.cpp.o
/home/daniel/git/torrent-file-editor/bencodemodel.cpp: In member function ‘void BencodeModel::appendRow(const QModelIndex&)’:
/home/daniel/git/torrent-file-editor/bencodemodel.cpp:562:32: error: unknown option after ‘#pragma GCC diagnostic’ kind [-Werror=pragmas]
 #pragma GCC diagnostic ignored "-Wdeprecated-copy"
                                ^~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
CMakeFiles/torrent-file-editor.dir/build.make:513: recipe for target 'CMakeFiles/torrent-file-editor.dir/bencodemodel.cpp.o' failed
make[2]: *** [CMakeFiles/torrent-file-editor.dir/bencodemodel.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/torrent-file-editor.dir/all' failed
make[1]: *** [CMakeFiles/torrent-file-editor.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

I am not sure where to proceed from here. Later I might have a look at the C++ code and see if I can figure something out.

**Comment by danieldeankon** [comment]
From this page https://www.gnu.org/software/gcc/gcc-9/changes.html

> New warnings:
>    -Wdeprecated-copy, implied by -Wextra, warns about the C++11 deprecation of implicitly declared copy constructor and assignment operator if one of them is user-provided. -Wdeprecated-copy-dtor also warns if the destructor is user-provided, as specified in C++11.

Looks like gcc 9 is required to build. My version of gcc 7.5.0 is the one available in Linux Mint 19.2 Cinnamon.

**Comment by drizt** [comment]
Seems need to add extra gcc version checking.

**Comment by danieldeankon** [comment]
For the record, commenting out that one line, #562 of bencodemodel.cpp, enabled me to run make successfully. The program builds and runs.

**Comment by drizt** [comment]
Can you find a correct way to disable this pragma for gcc verison which is not support it?

**Comment by danieldeankon** [comment]
The root cause of the failure to compile was that all compiler warnings were being treated as errors because of the -Werror flag being set in CMakeLists.txt. A disadvantage of using -Werror is that it tends to cause compilation to depend on specific versions of a compiler in ways that aren't clear at first. I've made a pull request #117 so that usage of pragma directives not recognised by GCC is no longer an error, but just a warning. This makes it more compatible with older versions while still allowing you to be strict about compiler warnings in general.
