### ISSUE TITLE
Remove Selected Files

### ISSUE THREAD

**Issue by kdantas** [torrent-file-editor/torrent-file-editor#135]
Hi, I don't know if I'm doing something wrong, but when I remove the selected files and click save, the .torrent file doesn't show any changes.

![TFE Delete](https://user-images.githubusercontent.com/19543277/189463460-a9f60fa3-7db8-40ed-8cba-254624ccba3d.JPG)

**Comment by drizt** [comment]
You need to rebuild torrent. Use hammer button. Also note that in this case hash of torrent file will be changed. You will get new torrent.

**Comment by kdantas** [comment]
Thanks. It would be nice a tutorial explaining each funcionality of the software.
