### ISSUE TITLE
How can I calculate the pieces root hash of a file in BitTorrent v2&hybrid torrent?

### ISSUE THREAD

**Issue by kovalensky** [torrent-file-editor/torrent-file-editor#137]
![2022-12-16_081111](https://user-images.githubusercontent.com/45331093/208141149-09c4e1b7-c65d-4fbb-973a-957b0a93c7cb.png)

**Comment by drizt** [comment]
Seems TFE doesn't support this feature.

**Comment by kovalensky** [comment]
> Seems TFE doesn't support this feature.

How do I do it programmatically?

**Comment by kovalensky** [comment]
Done,
