### ISSUE TITLE
CMakeLists.txt still mentions 0.3.17 version

### ISSUE THREAD

**Issue by xaizek** [torrent-file-editor/torrent-file-editor#143]
https://github.com/torrent-file-editor/torrent-file-editor/blob/207d5aea6dfaaa697839360a83622b2b19cfe193/CMakeLists.txt#L17

Same in 0.3.18 release tarball.

**Comment by drizt** [comment]
Thanks. Fixed in d17a3e06fc416c6b8c7577a017462d982538593b.
