### ISSUE TITLE
Italian language translation and external language file

### ISSUE THREAD

**Issue by bovirus** [torrent-file-editor/torrent-file-editor#147]
@drizt 

I completed the italian translation.
Some strings were not translated.
Some strings were marked as translated but were in english.
Please if you can to enable in crowdin the option to downlaod/uplaod .ts file for translations.

Please when you try to rebuild the exe file.

To help translator in translation please if you can modify teh source to enable the option to use an external language file (.ts.qm file).
In this way the transltor can test in place the translation.

Thanks.

**Comment by drizt** [comment]
Hello.

Probably do you mean this button?

![image](https://github.com/torrent-file-editor/torrent-file-editor/assets/534665/49073d1d-fbc0-4ecc-816f-fbc7156b590b)

I enable it now.

**Comment by drizt** [comment]
I think it's possible to add a button for translators to mannually apply own .qm file.

**Comment by bovirus** [comment]
@drizt

Yes in corwdin it's the option to works with offline file (download/upload).
Tested and it works in Crowdin.

About use external language file in the application I propose to modify teh source code to check at app startup if availbel in teh same foilder a language file torrentfileeditor_xx_xx.qm.
If you found it you will load it automatically.

In this way the translator can
- Download .ts file from Crowdin.
Make the chnages with QTLinguist and compile it as qm.
Made all test with application (suing external language file option without wait next build).
When the .ts file is OK it will uplaod in Crowdin.

Note., If you are interested I have ta recent QtLinguist (64bit) as installer or portable vesrion.

**Comment by bovirus** [comment]
@drizt

Please 

Please modify the source code andrebuild the app to enable the suer to load excternal langauge file for test.

Please syncronize .ts files in Github with latest chanjes in Crowdin.
If you can please plan an automtaic update from crowdin to guthub for language file (like one time of every two weeks).

**Comment by bovirus** [comment]
@drizt 

Thanks.

Please modify the source and rebuild app to enable using of external language.
It's important to test and tune the translation. 
Until that I cannot check translation in place.
Thanks.

**Comment by drizt** [comment]
Will do as can find a free time.

**Comment by drizt** [comment]
Atm you can recompile whole application with Qt Creator.

**Comment by bovirus** [comment]
@drizt

Any additional info how to compie with QTCreator?
What's the file name/project to laod in QTCreator?

**Comment by drizt** [comment]
Which OS you use?

**Comment by bovirus** [comment]
@drizt 

Sorry I forgot to mention it.
Windows 10 22H2 64bit.
Qt SDK 6.6.0 beta (MSVC 2019 64bit).
QT Creator 11.0.1
QT Design Studio 4.2.0

**Comment by drizt** [comment]
Then you need to install Qt 5.15.2 MinGW. In Qt Creator open `torrent-file-editor\CMakeListst.txt`

![2023-08-06_13-29](https://github.com/torrent-file-editor/torrent-file-editor/assets/534665/e534cbe6-baaa-4844-bda7-bf0f9392a61f)

![2023-08-06_13-29_1](https://github.com/torrent-file-editor/torrent-file-editor/assets/534665/5ef708c8-d76b-46f7-95cd-07bda419a021)

I made some changes to fix native Windows building in Qt Creator. Now it works. But only for Qt5. Qt6 requires some CMake fixes. Also I don't use MSVC so any building is not tested.

**Comment by bovirus** [comment]
@drizt 

Thanks for the info.
I will try.

If you are agree I propose you to add this info in README:MD how to compile source under Windows.

**Comment by drizt** [comment]
Just open CMakeListst.txt from repo as is. No need extra actions. You only need to have suitable Qt version and set build type (Release or Debug).

**Comment by bovirus** [comment]
@drizt 

Done but I got somne errors.
Where I sey debug/relase info as exoplained ion your first window?
What's tyour QT Creator version?

**Comment by drizt** [comment]
I use Latest Qt Creator. What errors?

**Comment by bovirus** [comment]
@drizt 

I tesetd in other pc and it seems that is working.

**Comment by drizt** [comment]
I build standalone.exe on Fedora 31 with MinGW from from Fedora repository. Look at README.md. For you case if you want to run TFE outside of Qt Creator you need to put some Qt libs near torrent-file-editor.exe.

**Comment by bovirus** [comment]
@drizt

I will wait next app build.
Please check report about language feels here

https://github.com/torrent-file-editor/torrent-file-editor/issues/148

There two strings untranslated (but seem sthat translation si available in language file)

There is a mismatch about language file in github and Vrowdin.
1 string more in Github then Crowdin (missing "&Copy" in Crowdin)
1 string (Pieces)  with different translation in github then Crowdin (the translation on Crowdin is right).

**Comment by drizt** [comment]
If something not working for you feel free to open a new issues. Also please open a new issue for each separate feature or but request. Don't mix all distinguish questions in one topic.

**Comment by bovirus** [comment]
@drizt 

Thanks.

I updated Italian language file on Crpodin.
Please update in on github.

If I will find other issues I will open separate tickets for them-
