### ISSUE TITLE
GUI issues - Strings not translated

### ISSUE THREAD

**Issue by bovirus** [torrent-file-editor/torrent-file-editor#148]
@drizt 

Pelase check screenshot

![image](https://github.com/torrent-file-editor/torrent-file-editor/assets/1262554/029ae34a-863a-427c-8a6f-5672f896c977)

![image](https://github.com/torrent-file-editor/torrent-file-editor/assets/1262554/b3ce2b5c-fab1-48bd-aa4f-d8e836c39226)

Please add relative strings to language file

Please check synchronize translation between crowdin and github.
Ex. string in italian language in github are 129 and in crowdin are 128 (the difference is "&Copy").
In github italian ts file there is a string  "Parti" ("Pieces") that is not available in Crowdin (it's "Segmenti").

**Comment by bovirus** [comment]
@drizt 

Thanks for sync language between github/Crowdin.

Please fix the issues regarding langauge reported in the screenshots.

**Comment by drizt** [comment]
No need to ask always to fix. You opened issues. I see it. When I can/want I will do them. Be patient.

**Comment by bovirus** [comment]
@drizt

I just mention because in previous github langauge file was avaiqlble "&Copy" (not translated and reported) but now the github language file is one string left (129 before / 128 now) and "&Copy" is not available anymore.
