### ISSUE TITLE
Will the modified torrent file size changed?

### ISSUE THREAD

**Issue by bonuschild** [torrent-file-editor/torrent-file-editor#153]
Hi,
I would like to edit a torrent file because it file size is about 8.6MB, which is too large for some platform to analyze. I've heard that the checksum is for the whole torrent file so that splitting torrent file into serveral pieces is not available.

## looking for help
Can I split the torrent file by size<=3MB?

**Comment by drizt** [comment]
In common case you can't. For splitting you need to generate new piece hashes. For this you need to have all original files. If you can them. You can create a new torrent files. So just download all files and create new torrent files from a scratch.
