### ISSUE TITLE
dont delete files atached to .torrent...

### ISSUE THREAD

**Issue by jeffbart** [torrent-file-editor/torrent-file-editor#158]
this tool dont delete files attachedo in the torrent file....

**Comment by drizt** [comment]
I don't understand anything. Please explain.

**Comment by jeffbart** [comment]
I have a torrent file with 80 files, I want to share only a part of them, when we delete them with this application, the files continue to appear in the torrent file

**Comment by drizt** [comment]
Yoo need rebuild torrent. Use hammer button but hash will be changed.
