### ISSUE TITLE
memory leak upon opening a specific torrent

### ISSUE THREAD

**Issue by rezad1393** [torrent-file-editor/torrent-file-editor#160]
OS:archlinux

I downloaded this torrent and wanted to see its content and it seems to make this app just use all the system memory and make it hang.

this is the torrent that causes this.
[buggy.tar.gz](https://github.com/user-attachments/files/16734624/buggy.tar.gz)

**Comment by drizt** [comment]
You provide invalid .torrent file. Seems it cut. Maybe you downloaded it partially. Anyway I fixed crash. Thanks.

**Comment by rezad1393** [comment]
> You provide invalid .torrent file. Seems it cut. Maybe you downloaded it partially. Anyway I fixed crash. Thanks.

I undertstand but the issue is the memory leak.
 a bad torrent file should not make the app memory runaway usage.
that is the more important bug.

**Comment by drizt** [comment]
Fixed. See commit.

**Comment by rezad1393** [comment]
> Fixed. See commit.

sorry.
I read your anser as you fixing a crash but because it was not a app crash but memory leak that causes OS crash (hang technically) I wanted to be sure that it was the leak that got fixed.


thank you.

**Comment by rezad1393** [comment]
> I used debug build for development. In debug crash happens. Not memory leak. In release build it bug should lead to memory leak problem. With release build when I will publish new version problem must gone.

how so?
I am not a developer, so what that means?
in debug mode the app crashes, but in normal mode it doesnt?

because for me it doesnt crash (its gui is not shown but the process is running) and just its memory usage runs away.
