### ISSUE TITLE
only one tracker is shown

### ISSUE THREAD

**Issue by rezad1393** [torrent-file-editor/torrent-file-editor#161]
this torrent only shows one tracker even though it has two.

[i2pupdate.zip](https://github.com/user-attachments/files/16881445/i2pupdate.zip)

**Comment by drizt** [comment]
TFE expects `announce-list` in some specific format `[[tracker1], [tracker2], [tracker3]]`. i2pupdate.zip.torrent has `announce-list` in form `[[tracker1, tracker2]]`. Maybe need to read `announce-list` in any form and then save in form `[[tracker1], [tracker2], [tracker3]]`. Atm I don't know the best way how to do this. But I don't want make any changes to **Main** tab and add support for various form of `announce-list`. If need specific form it can be edited in **Tree** tab.
