### ISSUE TITLE
Check for Update Fails

### ISSUE THREAD

**Issue by smaragdus** [torrent-file-editor/torrent-file-editor#87]
Update check does not work, screen:

![Torrent File Editor 0 3 13 - 2019-04-12 - update check - 002](https://user-images.githubusercontent.com/9025757/56012565-b9797b00-5cf5-11e9-981d-64d330bc3d52.png)

The screen-shot is taken from version [0.3.13](https://sourceforge.net/projects/torrent-file-editor/files/v0.3.13/) but the same happens wiith version [0.3.14](https://sourceforge.net/projects/torrent-file-editor/files/v0.3.14/). Please confirm the problem.

**Comment by drizt** [comment]
What your Windows version?

**Comment by smaragdus** [comment]
@drizt 

> What your Windows version?

**Windows 8 x64**

I didn't mention my OS version in my first post because I didn't think that the problem might be OS-dependent, sorry.

**Comment by drizt** [comment]
> but I thought I should report the problem since I encountered it,

You're welcome. You get notification from github but not each app user has github account and subscribed to TFE repo.

**Comment by drizt** [comment]
I changed hosting. Please check it now with latest tfe. Actually appcast.json was moved from SourceForge to Github.

**Comment by smaragdus** [comment]
@drizt 

I tested `Check for Update` using **Torrent File Editor** version [0.3.15](https://github.com/torrent-file-editor/torrent-file-editor/releases/tag/v0.3.15) (x64) but it did not work for me showing the same error message:

`Something went wrong`

**screen:**

![Torrent File Editor 0 3 15 - 2019-04-23 - update check - 002](https://user-images.githubusercontent.com/9025757/56539270-079c4300-656e-11e9-8f5e-382f0afca2d7.png)

Is `Check for Update` working for you?

**Comment by drizt** [comment]
Thanks.

**Comment by smaragdus** [comment]
@drizt 

I checked versions [0.3.16](https://github.com/torrent-file-editor/torrent-file-editor/releases/tag/v0.3.16) and [0.3.17](https://github.com/torrent-file-editor/torrent-file-editor/releases/tag/v0.3.17) and it seems that **Check for Update** has been fixed, screens:

**Torrent File Editor 0.3.16**

![Torrent File Editor 0 3 16 - 2020-03-26 - 004](https://user-images.githubusercontent.com/9025757/77598532-bc6f7a80-6f0a-11ea-94c3-1013bc5be307.png)

**Torrent File Editor 0.3.17**

![Torrent File Editor 0 3 17 - 2020-03-26 - 004](https://user-images.githubusercontent.com/9025757/77598550-ca250000-6f0a-11ea-99de-f5f69e859d4a.png)

So I will close this issue, thanks and regards.
