### ISSUE TITLE
Font change for partial viewing of long strings

### ISSUE THREAD

**Issue by stevenlele** [torrent-file-editor/torrent-file-editor#88]
I'm using Windows 10 under Chinese (simplified) locale.

The font of the text changes when I adjusts the width of the column to fully show a long string which was cut short with an ellipsis (`…`).

![](https://user-images.githubusercontent.com/15964380/56025217-421f0800-5d44-11e9-939f-b1d739f8e8b8.png)

**Left:** The text is `blah blah blah …`, cut short with an ellipsis (`…`). The font is SimSun, which is a (partly monospace) fallback font in Windows 10 (Simplified Chinese locale). It is different from the other texts in the list contents, which are in Microsoft Yahei, the default font.

**Right:** The text is `blah blah blah blah blah`, fully displayed because I made the column wide. The font is correct now.

![](https://user-images.githubusercontent.com/15964380/56025593-0173be80-5d45-11e9-8f87-c09e8fb3b744.png)

Same in the tree view.

I guess it's because of the ellipsis `…` (U+2026). Maybe this can be fixed by changing the ellipsis into three dots (`...`).

This is a minor issue, but I hope it can be fixed 😃

**Comment by drizt** [comment]
Seems it is Qt internal.
